---
name: DateTime-Format-DateParse
version: 0.04
author:
  - 'Joshua Hoblitt (JHOBLITT) <jhoblitt@cpan.org>'
abstract: Parses Date::Parse compatible formats
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Date::Parse: 2.27
  DateTime: 0.29
  DateTime::TimeZone: 0.27
  Time::Zone: 2.22
provides:
  DateTime::Format::DateParse:
    file: lib/DateTime/Format/DateParse.pm
    version: 0.04
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
