---
name: DateTime-Format-DateParse
version: 0.01
author: ~
abstract: ~
license: perl
provides:
  DateTime::Format::DateParse:
    file: lib/DateTime/Format/DateParse.pm
    version: 0.01
generated_by: Module::Build version 0.25
